/* Generated by Yosys 0.64+68 (git sha1 413169663, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module UMC_8000(clk, rst, mem_rdata, instru, mem_wdata, pc, mem_addr, mem_write);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [7:0] mem_rdata;
  wire [7:0] mem_rdata;
  input [7:0] instru;
  wire [7:0] instru;
  output [7:0] mem_wdata;
  wire [7:0] mem_wdata;
  output [7:0] pc;
  wire [7:0] pc;
  output [5:0] mem_addr;
  wire [5:0] mem_addr;
  output mem_write;
  wire mem_write;
  wire is_end;
  wire mem_in;
  wire sum_en;
  wire sum_in;
  wire sum_out;
  controller u_controller (
    .instru(instru),
    .is_end(is_end),
    .mem_addr(mem_addr),
    .mem_in(mem_in),
    .mem_write(mem_write),
    .sum_en(sum_en),
    .sum_in(sum_in),
    .sum_out(sum_out)
  );
  datapath u_datapath (
    .clk(clk),
    .mem_in(mem_in),
    .mem_rdata(mem_rdata),
    .mem_wdata(mem_wdata),
    .rst(rst),
    .sum_en(sum_en),
    .sum_in(sum_in),
    .sum_out(sum_out)
  );
  pc u_pc (
    .clk(clk),
    .is_end(is_end),
    .pc(pc),
    .rst(rst)
  );
endmodule

module adder(a1, a2, out);
  input [7:0] a1;
  wire [7:0] a1;
  input [7:0] a2;
  wire [7:0] a2;
  output [7:0] out;
  wire [7:0] out;
  wire [7:0] _00_;
  wire [7:0] _01_;
  wire [7:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  assign out[1] = _01_[1] ^ _00_[0];
  assign out[2] = _01_[2] ^ _00_[1];
  assign out[3] = _01_[3] ^ _00_[2];
  assign out[4] = _01_[4] ^ _00_[3];
  assign out[5] = _01_[5] ^ _00_[4];
  assign out[6] = _01_[6] ^ _00_[5];
  assign out[7] = _01_[7] ^ _00_[6];
  assign _00_[0] = a1[0] & a2[0];
  assign _02_[1] = a1[1] & a2[1];
  assign _02_[2] = a1[2] & a2[2];
  assign _02_[3] = a1[3] & a2[3];
  assign _02_[4] = a1[4] & a2[4];
  assign _02_[5] = a1[5] & a2[5];
  assign _02_[6] = a1[6] & a2[6];
  assign out[0] = a1[0] ^ a2[0];
  assign _01_[1] = a1[1] ^ a2[1];
  assign _01_[2] = a1[2] ^ a2[2];
  assign _01_[3] = a1[3] ^ a2[3];
  assign _01_[4] = a1[4] ^ a2[4];
  assign _01_[5] = a1[5] ^ a2[5];
  assign _01_[6] = a1[6] ^ a2[6];
  assign _01_[7] = a1[7] ^ a2[7];
  assign _00_[2] = _02_[2] | _10_;
  assign _10_ = _01_[2] & _00_[1];
  assign _11_ = _01_[4] & _00_[3];
  assign _00_[5] = _14_ | _09_;
  assign _09_ = _08_ & _00_[3];
  assign _12_ = _01_[6] & _00_[5];
  assign _00_[6] = _02_[6] | _12_;
  assign _00_[3] = _13_ | _06_;
  assign _06_ = _07_ & _00_[1];
  assign _08_ = _01_[5] & _01_[4];
  assign _14_ = _02_[5] | _05_;
  assign _05_ = _01_[5] & _02_[4];
  assign _07_ = _01_[3] & _01_[2];
  assign _13_ = _02_[3] | _04_;
  assign _04_ = _01_[3] & _02_[2];
  assign _00_[4] = _02_[4] | _11_;
  assign _00_[1] = _02_[1] | _03_;
  assign _03_ = _01_[1] & _00_[0];
  assign _01_[0] = out[0];
  assign _02_[0] = _00_[0];
endmodule

module controller(instru, mem_addr, is_end, mem_in, sum_en, sum_in, sum_out, mem_write);
  input [7:0] instru;
  wire [7:0] instru;
  output [5:0] mem_addr;
  wire [5:0] mem_addr;
  output is_end;
  wire is_end;
  output mem_in;
  wire mem_in;
  output sum_en;
  wire sum_en;
  output sum_in;
  wire sum_in;
  output sum_out;
  wire sum_out;
  output mem_write;
  wire mem_write;
  wire _00_;
  wire _01_;
  wire [1:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [23:0] _07_;
  wire [5:0] _08_;
  wire _09_;
  wire [5:0] code;
  wire [1:0] opcode;
  assign _00_ = ~instru[0];
  assign _01_ = ~instru[1];
  assign _04_ = _00_ | _01_;
  assign _05_ = instru[0] | _01_;
  assign _06_ = _00_ | instru[1];
  assign _08_[3] = _07_[8] | _07_[21];
  assign _02_[0] = _07_[5] | _07_[8];
  assign _02_[1] = _07_[12] | _07_[21];
  assign _09_ = _02_[0] | _02_[1];
  assign _03_ = instru[0] | instru[1];
  assign _07_[5] = ~_04_;
  assign _07_[8] = ~_05_;
  assign _07_[12] = ~_06_;
  assign _07_[21] = ~_03_;
  assign mem_write = _09_ ? _07_[12] : 1'hx;
  assign sum_en = _09_ ? _08_[3] : 1'hx;
  assign mem_in = _09_ ? _07_[8] : 1'hx;
  assign is_end = _09_ ? _07_[5] : 1'hx;
  assign { _07_[23:22], _07_[20:13], _07_[11:9], _07_[7:6], _07_[4:0] } = { 9'h000, _07_[12], 1'h0, _07_[8], _07_[8], 7'h00 };
  assign { _08_[5:4], _08_[2:0] } = { _07_[5], _07_[8], _07_[8], _07_[12], _07_[12] };
  assign opcode = instru[1:0];
  assign code = { is_end, mem_in, sum_en, mem_in, mem_write, mem_write };
  assign sum_out = mem_write;
  assign sum_in = mem_in;
  assign mem_addr = instru[7:2];
endmodule

module datapath(clk, rst, mem_in, sum_in, sum_out, sum_en, mem_rdata, mem_wdata);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input mem_in;
  wire mem_in;
  input sum_in;
  wire sum_in;
  input sum_out;
  wire sum_out;
  input sum_en;
  wire sum_en;
  input [7:0] mem_rdata;
  wire [7:0] mem_rdata;
  output [7:0] mem_wdata;
  wire [7:0] mem_wdata;
  wire [7:0] adder_to_sum;
  wire [7:0] mem_to_adder;
  wire [7:0] mem_to_sum;
  wire [7:0] sum_input;
  wire [7:0] sum_output;
  wire [7:0] sum_to_adder;
  adder adder (
    .a1(mem_to_adder),
    .a2(sum_to_adder),
    .out(adder_to_sum)
  );
  demux mem_in_demux (
    .din(mem_rdata),
    .dout0(mem_to_sum),
    .dout1(mem_to_adder),
    .sel(mem_in)
  );
  register sum (
    .clk(clk),
    .din(sum_input),
    .dout(sum_output),
    .en(sum_en),
    .rst(rst)
  );
  mux sum_in_mux (
    .din0(mem_to_sum),
    .din1(adder_to_sum),
    .dout(sum_input),
    .sel(sum_in)
  );
  demux sum_out_demux (
    .din(sum_output),
    .dout0(sum_to_adder),
    .dout1(mem_wdata),
    .sel(sum_out)
  );
endmodule

module demux(din, sel, dout0, dout1);
  input [7:0] din;
  wire [7:0] din;
  input sel;
  wire sel;
  output [7:0] dout0;
  wire [7:0] dout0;
  output [7:0] dout1;
  wire [7:0] dout1;
  assign dout1[1] = sel ? din[1] : 1'h0;
  assign dout1[2] = sel ? din[2] : 1'h0;
  assign dout1[3] = sel ? din[3] : 1'h0;
  assign dout1[4] = sel ? din[4] : 1'h0;
  assign dout1[5] = sel ? din[5] : 1'h0;
  assign dout1[6] = sel ? din[6] : 1'h0;
  assign dout1[7] = sel ? din[7] : 1'h0;
  assign dout0[0] = sel ? 1'h0 : din[0];
  assign dout0[1] = sel ? 1'h0 : din[1];
  assign dout0[2] = sel ? 1'h0 : din[2];
  assign dout0[3] = sel ? 1'h0 : din[3];
  assign dout0[4] = sel ? 1'h0 : din[4];
  assign dout0[5] = sel ? 1'h0 : din[5];
  assign dout0[6] = sel ? 1'h0 : din[6];
  assign dout0[7] = sel ? 1'h0 : din[7];
  assign dout1[0] = sel ? din[0] : 1'h0;
endmodule

module mux(din0, din1, sel, dout);
  input [7:0] din0;
  wire [7:0] din0;
  input [7:0] din1;
  wire [7:0] din1;
  input sel;
  wire sel;
  output [7:0] dout;
  wire [7:0] dout;
  assign dout[0] = sel ? din1[0] : din0[0];
  assign dout[1] = sel ? din1[1] : din0[1];
  assign dout[2] = sel ? din1[2] : din0[2];
  assign dout[3] = sel ? din1[3] : din0[3];
  assign dout[4] = sel ? din1[4] : din0[4];
  assign dout[5] = sel ? din1[5] : din0[5];
  assign dout[6] = sel ? din1[6] : din0[6];
  assign dout[7] = sel ? din1[7] : din0[7];
endmodule

module pc(clk, rst, is_end, pc);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input is_end;
  wire is_end;
  output [7:0] pc;
  reg [7:0] pc;
  wire _00_;
  wire _01_;
  wire _02_;
  wire [31:0] _03_;
  wire [31:0] _04_;
  wire [31:0] _05_;
  wire _06_;
  wire _07_;
  reg halt;
  always @(posedge clk, negedge rst)
    if (!rst) pc[0] <= 1'h0;
    else if (_00_) pc[0] <= _04_[0];
  always @(posedge clk, negedge rst)
    if (!rst) pc[1] <= 1'h0;
    else if (_00_) pc[1] <= _05_[1];
  always @(posedge clk, negedge rst)
    if (!rst) pc[2] <= 1'h0;
    else if (_00_) pc[2] <= _05_[2];
  always @(posedge clk, negedge rst)
    if (!rst) pc[3] <= 1'h0;
    else if (_00_) pc[3] <= _05_[3];
  always @(posedge clk, negedge rst)
    if (!rst) pc[4] <= 1'h0;
    else if (_00_) pc[4] <= _05_[4];
  always @(posedge clk, negedge rst)
    if (!rst) pc[5] <= 1'h0;
    else if (_00_) pc[5] <= _05_[5];
  always @(posedge clk, negedge rst)
    if (!rst) pc[6] <= 1'h0;
    else if (_00_) pc[6] <= _05_[6];
  always @(posedge clk, negedge rst)
    if (!rst) pc[7] <= 1'h0;
    else if (_00_) pc[7] <= _05_[7];
  always @(posedge clk, negedge rst)
    if (!rst) halt <= 1'h0;
    else if (is_end) halt <= 1'h1;
  assign _04_[0] = ~pc[0];
  assign _05_[1] = pc[1] ^ pc[0];
  assign _05_[2] = pc[2] ^ _03_[1];
  assign _05_[3] = pc[3] ^ _03_[2];
  assign _05_[4] = pc[4] ^ _03_[3];
  assign _05_[5] = pc[5] ^ _03_[4];
  assign _05_[6] = pc[6] ^ _03_[5];
  assign _05_[7] = pc[7] ^ _03_[6];
  assign _03_[6] = pc[6] & _03_[5];
  assign _03_[4] = pc[4] & _03_[3];
  assign _03_[2] = pc[2] & _03_[1];
  assign _03_[5] = _07_ & _03_[3];
  assign _03_[3] = _06_ & _03_[1];
  assign _07_ = pc[5] & pc[4];
  assign _06_ = pc[3] & pc[2];
  assign _03_[1] = pc[1] & pc[0];
  assign _01_ = ~halt;
  assign _02_ = ~is_end;
  assign _00_ = _01_ & _02_;
  assign { _03_[31:8], _03_[0] } = { 24'h000000, pc[0] };
  assign _04_[31:1] = { 24'h000000, pc[7:1] };
  assign { _05_[31:8], _05_[0] } = { 23'h000000, _03_[7], _04_[0] };
endmodule

module register(clk, rst, en, din, dout);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input en;
  wire en;
  input [7:0] din;
  wire [7:0] din;
  output [7:0] dout;
  reg [7:0] dout;
  always @(posedge clk, negedge rst)
    if (!rst) dout[0] <= 1'h0;
    else if (en) dout[0] <= din[0];
  always @(posedge clk, negedge rst)
    if (!rst) dout[1] <= 1'h0;
    else if (en) dout[1] <= din[1];
  always @(posedge clk, negedge rst)
    if (!rst) dout[2] <= 1'h0;
    else if (en) dout[2] <= din[2];
  always @(posedge clk, negedge rst)
    if (!rst) dout[3] <= 1'h0;
    else if (en) dout[3] <= din[3];
  always @(posedge clk, negedge rst)
    if (!rst) dout[4] <= 1'h0;
    else if (en) dout[4] <= din[4];
  always @(posedge clk, negedge rst)
    if (!rst) dout[5] <= 1'h0;
    else if (en) dout[5] <= din[5];
  always @(posedge clk, negedge rst)
    if (!rst) dout[6] <= 1'h0;
    else if (en) dout[6] <= din[6];
  always @(posedge clk, negedge rst)
    if (!rst) dout[7] <= 1'h0;
    else if (en) dout[7] <= din[7];
endmodule
